from __future__ import annotations

import re
import sys
from pathlib import Path


REVISED_CHAPTER = r'''\chapter{Limitations and Threats to Validity}
\label{ch:limitations}

This chapter defines how far the reported findings can be interpreted. The main limits concern benchmark and construct validity, synthetic data, complete-system comparisons, statistical and artifact coverage, and the absence of representative clinical validation.

\section{Benchmark and Measurement Limitations}

The computational results measure agreement with dataset-provided diagnoses after the parent-label projection defined in Chapter~\ref{ch:data}. They do not measure agreement with independently adjudicated clinical diagnoses. The internal benchmark contains one projected parent in 912 cases, two in 83 cases, and three in five cases. Committed Top-1 counts a case as correct when the committed primary matches any projected benchmark parent. The first-listed parent is used only in clearly marked single-label descriptions, such as the confusion matrix.

The metrics describe different output views. Top-1 evaluates the committed primary. Genuine Top-3 evaluates an ordered candidate list. Exact Match and F1 evaluate the complete emitted set and are affected by output cardinality. Single's emitted-label hit@3 is not the same as HiED's genuine ranked Top-3. These measures should not be merged into one general accuracy claim.

The parent-label projection also changes the level of agreement being measured. F41 and F43 subtype predictions are collapsed to their parent labels, so parent-level agreement can conceal subtype-level disagreement. In addition, \emph{Others} is an evaluation-only class and cannot be ranked, checked, or emitted by HiED. Cases mapped to \emph{Others} are therefore not symmetric with the configured diagnoses and are excluded from the checker-eligible compatibility analysis. Results on the checker-eligible population are conditional results rather than estimates for all internal cases.

The $D_3$, $I$, and $S$ indicators describe different recorded views. They are not a chronological or causal funnel. The criterion-compatible set is an operational result under study-specific rules, not a ranked primary-diagnosis recommendation. The gold-informed oracle directly uses benchmark labels and is a non-deployable optimistic bound rather than an evaluated selector.

Criterion compatibility introduces an additional construct limitation. The criterion states are generated by the model, and the compatible set is then formed by study-specific deterministic rules. Neither the criterion states nor the compatibility decisions have independent criterion-level gold annotations. Errors in evidence extraction, state assignment, criterion wording, or rule thresholds can therefore change gold-label inclusion ($I$) and the resulting $D_3/I/S$ profiles. The compatible set should be interpreted as an operational study output, not an independently validated clinical judgment.

The framework can show where disagreement is recorded, but not why it occurred. It cannot reveal hidden model reasoning, identify the uniquely correct clinical primary diagnosis, or prove that a localized disagreement is automatically recoverable.

\section{Dataset and Generalizability Limitations}

LingxiDiag-16K and MDD-5k contain synthetic Chinese psychiatric dialogues. They are useful for controlled evaluation, but they may have regular wording, simplified ambiguity, clearer symptom cues, limited comorbidity, and less longitudinal or conversational complexity than natural psychiatric interviews. Similar findings across them may reflect shared properties of synthetic generation rather than general properties of clinical diagnosis.

The main internal set is a fixed 1,000-case held-out subset sampled from the LingxiDiag training source because the official test split was unavailable. Case identifiers were excluded from training and retrieval, but the held-out cases still share the source generator, language style, label distribution, and annotation process with development data. A complete semantic near-duplicate audit was not performed. The result is therefore same-source held-out performance, not independent external validation.

The public-validation split was repeatedly used for prompt development, rule refinement, sensitivity analysis, and retrieval selection. It is therefore development evidence rather than an independent performance estimate, and repeated use may have adapted design decisions to the specific cases in that split. The reversal between validation and held-out retrieval ordering illustrates the uncertainty of selecting a configuration from one limited development split.

MDD-5k provides a second synthetic source, not a clinical cohort. The archived MDD-5k outputs also contain more than one trace lineage. The matched method-comparison trace, canonical rescore, and historical output are not interchangeable. The main external claims use one matched trace, while the canonical trace is reported only as sensitivity evidence. Mixing fields across these traces would not reproduce one system run.

The cross-corpus TF--IDF results show that same-source prediction can depend strongly on wording and label priors. The completed evidence therefore supports same-source held-out analysis and a bounded second-synthetic-source test. It does not establish generalization to real psychiatric consultations, independent hospitals, spontaneous or code-switched Taiwanese conversations, or Taiwanese coding practice.

\section{Model and Experimental-Comparison Limitations}
\label{sec:model-comparison-limitations}

Most comparisons change more than one component. The main table compares complete TF--IDF, Single, and HiED configurations on the same cases and label mapping, but the methods differ in training, retrieval, prompts, model calls, intermediate outputs, and output contract. Their performance differences cannot be assigned only to multi-agent orchestration.

Retrieval comparisons are controlled within each architecture, but global Top-5 and parent-balanced retrieval still differ in example count, composition, ordering, similarity, label balance, and prompt length. Single and HiED also selected their retrieval settings separately on validation, so their main configurations are not retrieval matched.

The model-based components are not independent expert votes. They use the same fixed transcript and may share base-model priors, lexical preferences, and failure modes. Agreement among agents or paths therefore does not provide independent confirmation. The study does not isolate whether an observed difference is caused by role decomposition, prompt structure, additional inference, compute budget, or the number of agents.

DA versus NtS is the most controlled finalization comparison because the upstream HiED records are shared. Even so, it tests one NtS rule rather than all criterion-based selectors. DA may also emit a comorbid diagnosis while NtS emits one primary diagnosis, so their set-based metrics do not isolate primary re-selection.

Deterministic fusion applies one fixed rule. Pairwise comparison, debate, self-consistency, and confidence-informed self-consistency change prompts, inference calls, context, aggregation, or budget. They are complete-configuration comparisons. The model-scale analysis is limited to the tested Qwen3 family and does not establish robustness across unrelated models or deployment settings.

No supported quantitative conclusion is drawn from the earlier F60 scope-expansion experiment because its source artifact was not preserved in the frozen repository snapshot.

\section{Statistical, Artifact, and Reproducibility Limitations}
\label{sec:statistical-reproducibility-limitations}

Confidence intervals and tests describe uncertainty over the observed cases under fixed outputs. They do not include uncertainty from benchmark validity, prompt design, model selection, synthetic generation, or a future population. A confidence interval that includes zero is not evidence of equivalence. A difference with an interval that excludes zero still does not identify a causal component when several parts of a configuration changed.

The 77,998 diagnosis-by-criterion states are clustered within cases, configured diagnoses, and checker templates rather than independent observations. The criterion-state analysis therefore summarizes each case before group averaging and remains descriptive. No hierarchical model or criterion-level population inference is reported.

Some groups are small or imbalanced. In particular, the 12-case $D_3=1,I=0,S=0$ group cannot support a stable class-specific conclusion. The repeated F41-to-F32 direction is a benchmark-relative pattern, not a clinically adjudicated confusion mechanism.

Artifact completeness also differs across analyses. The internal HiED headline row, the internal $D_3/I/S$ profiles, the paired DA--NtS comparison, and the matched external trace have case-level support. Several baseline and supporting results remain available only as aggregate summaries or incomplete records. These results cannot support new paired confidence intervals, case-overlap claims, or claims about which individual cases changed.

Reproduction requires the full evaluation contract: data split, model and prompt, retrieval configuration, diagnostic scope, recorded output lineage, label projection, eligible population, output-view definition, and statistical procedure. A similar number obtained with a different Top-3 definition, denominator, trace lineage, or compatibility rule is not the same result.

\section{Clinical Validity and Deployment Boundaries}
\label{sec:clinical-deployment-boundaries}

The benchmark-disagreement profiles cannot determine whether a mismatch comes from the system, missing transcript evidence, or the dataset label. The benchmark diagnoses have not been independently adjudicated as unique clinical primaries, and the criterion states and evidence notes remain model-generated.

The blinded LingxiDiag psychiatrist annotation study described in Section~\ref{sec:clinical-evaluation-plan} is the only clinician-facing study retained in this thesis. It uses a purposively selected sample of synthetic disagreement cases. Until completed, it provides no clinician evidence. Even after completion, it can assess how psychiatrists interpret the selected synthetic cases, but it cannot estimate clinical accuracy, diagnostic prevalence, workflow benefit, or performance in a representative patient population.

HiED does not have a clinically validated unknown-class detector, abstention rule, referral policy, confidence calibration, or targeted follow-up policy. The \emph{Others} class is used only for evaluation and cannot be emitted by the current system. No claim is made about treatment decisions, patient outcomes, subgroup fairness, hospital workflow, clinician workload, or safety.

HiED is motivated by Chinese-language psychiatric diagnosis and the Taiwanese clinical context, but the evaluated data are synthetic and do not represent natural Taiwanese consultations, local coding practice, or hospital workflow. The thesis therefore does not establish effectiveness in Taiwanese clinical practice or in other healthcare settings. HiED should remain an offline research and review framework until it is evaluated with independently adjudicated natural data, prospective workflow and safety studies, privacy and governance controls, and monitoring and revalidation procedures.

\section{Chapter Summary}

Within these limitations, the completed evidence supports three bounded claims: same-source benchmark comparison on the fixed internal split, stage-wise characterization of preserved outputs from synthetic transcripts, and a source-sensitivity analysis using a second synthetic corpus. It does not establish clinical correctness, the causal effect of individual system components, or deployment readiness. Stronger claims require independently adjudicated natural clinical data and controlled prospective evaluation.

'''


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: apply_ch10_limitations_revision.py TARGET_TEX")

    path = Path(sys.argv[1])
    text = path.read_text(encoding="utf-8")
    pattern = (
        r"\\chapter\{Limitations and Threats to Validity\}\n"
        r"\\label\{ch:limitations\}\n.*?"
        r"(?=\\chapter\{Conclusions and Future Work\})"
    )
    revised, count = re.subn(
        pattern,
        lambda _match: REVISED_CHAPTER,
        text,
        count=1,
        flags=re.DOTALL,
    )
    if count != 1:
        raise RuntimeError(f"expected exactly one Chapter 10 block, found {count}")

    path.write_text(revised, encoding="utf-8")
    print(f"Applied Chapter 10 limitations revision to {path}")


if __name__ == "__main__":
    main()
